baseURL = "https://lizrotenblog.netlify.com/blog/"
languageCode = "en-us"
title = "Liz Roten"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
relativeURLs = true

googleAnalytics = ""
disqusShortname = ""
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	subtitle = ""
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	copyright = "&copy;2019 Liz Roten"
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	dateFormat = "2006/01/02"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[taxonomies]
   tag = "tags"
