baseURL = "https://lizrotenblog.netlify.com/"
languageCode = "en-us"
title = "Liz Roten"
theme = "ezhil"

relativeURLs = true

googleAnalytics = ""
disqusShortname = "eroten-info"
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	subtitle = "a data science blog"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	copyright = "&copy;2019 Liz Roten"
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	dateFormat = "2006/01/02"
	
	customCSS = "css/atelier-forest-light.css"
	customJS = ["js/highlight.pack.js"]

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/lizroten"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/eroten"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[taxonomies]
   tag = "tags"
